project:
  type: website
  output-dir: docs
website:
  title: "Madison Ell"
  site-url: https://mell00.github.io/quarto-website-main/

  reader-mode: true
  navbar:
    title: false
    background: white
    foreground: "gray-800"
    collapse-below: sm  
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: /static/CV.pdf
        text: CV
    right: 
      - icon: github
        menu:
          - text: Website Source Code
            url:  https://mell00.github.io/quarto-website-main/
          - text: Github Profile
            url:  https://github.com/mell00
  page-footer:
    right: "&copy; 2024, Madison Ell"
#  comments:
#    utterances:
#      repo: mell00/quarto-website-main
    
# Format-specific Metadata
format:
  html:
    theme:
      - sandstone
      - styles.scss
    toc: false
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em

execute:
  freeze: auto

