project:
  type: website
  execute-dir: project

website:
  title: "Madison Ell"
  reader-mode: true
  navbar:
    title: false
    background: white
    foreground: "gray-800"
    collapse-below: sm  
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
    right: 
      - icon: github
        menu:
          - text: Website Source Code
            url:  https://github.com/mell00/quarto-website
          - text: Github Profile
            url:  https://github.com/mell00
  page-footer:
    right: "&copy; 2024, Madison Ell"
#  comments:
#    utterances:
#      repo: mell00/quarto-website
    
# Format-specific Metadata
format:
  html:
    theme:
      - sandstone
      - styles.scss
    toc: false
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em

execute:
  freeze: auto

