---
comments: false
---

## Publications

1.  Williams, J., Bade, I., Arora, S., Ell, M., Shen, G., Udata, S., Afghani, B. Use of aromatherapy
as a complementary therapy in alleviating chemotherapy related adverse effects in cancer
patients. Journal of Investigative Medicine, 68, 1, American Federation for Medical Research, 2020,
University of Southern California, Los Angeles, CA; University of California Irvine, Irvine, CA; CHOC
Hospital of Orange County, Orange, CA. [[PDF]](/static/Aromatherapy.pdf "PDF")

## Posters

1. Ell, M., Adams, D., Thiemann, E., Wordsworth, R., Wong, M. L., Mayyasi, M., Yung, Y. L. (2024,
December 9-13). Hydrogen escape from the Martian upper atmosphere during the Septem-
ber 2017 X8.2 solar flare [Conference presentation].
American Geophysical Union 2024, Washington, D.C., United States.
https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1533900

2. Ell, M., Klingbeil, S., Higgins, D., Wilson, N., Liebner, J. (2023, January 4-7). Improving Bayesian
methods for locating breakpoints in time series data [Conference presentation].
2023 Joint Mathematics Meetings, Boston, MA, United States.
https://meetings.ams.org/math/jmm2023/meetingapp.cgi/Paper/15315

3. Ell, M. (2022, November 17). Research Experiences for Undergraduates (REU) with a Fullerton College student [Conference presentation]. 
Fullerton College, Fullerton, CA, United States.

4. Ell, M. (2022, August 18). Improving Bayesian methods for locating breakpoints in time
series data [Conference presentation].
Pacific Summer Open Mathematics Seminar (PSOMS), Fullerton, CA, United States.